version: '3.7'
services:
    app:
        build: '.'
        command: 'python manage.py runserver 0.0.0.0:8000'
        init: true
        volumes:
            - './app:/src'
            - './.data/db.sqllite:/data/db.sqllite'
            - './.public:/public'
        env_file: '.env'
        ports:
            - '8000:8000'
        environment:
            DEBUG: 'True'
