# Generated by Django 3.0 on 2022-10-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_crawled_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
