# Generated by Django 3.0 on 2022-11-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_last_crawled_dttm'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_source__90c628_idx',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='source',
            new_name='venue',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue'], name='events_even_venue_i_f3b114_idx'),
        ),
    ]
