# Generated by Django 3.0 on 2022-11-03 03:13

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20221102_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=255)),
                ('all_day', models.BooleanField(default=False)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('last_crawled_dttm', models.DateTimeField(blank=True, null=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_events', to='events.EventSource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
