# Generated by Django 3.0 on 2022-11-04 14:49

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20221102_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RecurringEvent',
        ),
    ]
