# Generated by Django 3.0 on 2022-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20221104_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_dttm',
            field=models.DateTimeField(),
        ),
    ]
