# Generated by Django 3.0 on 2022-11-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20221104_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsource',
            name='extra_search_terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
