# Generated by Django 3.0 on 2022-11-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventsource_extra_search_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
